for iIteration = 1:CFG.STAGE_2.NumClustEval_nIterations
    disp(['Num. Clust. Evaluation: Iteration ', num2str(iIteration), ' / ', num2str(CFG.STAGE_2.NumClustEval_nIterations), ' ...' ]);
    evalutationObject = evalclusters( dataToTest, ...
				      CFG.STAGE_2.NumClustEval_methodName, ...
				      CFG.STAGE_2.NumClustEval_criterionType, ...
				      'klist',    CFG.STAGE_2.NumClustEval_kList, ...
				      'Distance', CFG.STAGE_2.NumClustEval_distanceMetric);

    clusteringEvaluation.optNumClustersAllIter(iIteration) = evalutationObject.OptimalK;
    idx = find(evalutationObject.InspectedK == evalutationObject.OptimalK);
    clusteringEvaluation.criterionValues(iIteration) = evalutationObject.CriterionValues(idx);
end % NumClustEval_nIterations
