function saveRngSerialInfo(savePathAndFilename, iJob, testVec)
%%
% Function to save: 
%
% - test numbers generated by the random number generator
% (numbers stored in testVec).
%
% - seed value (positive integer value)
%%

if iJob == 0
    suffix = '_root';
else
    suffix = ['_job', num2str(iJob)];
end

r = rng;
seed = r.Seed;
s_path = [savePathAndFilename, suffix, '.mat'];
s_path = fixPath(s_path);
save(s_path, 'testVec', 'seed')
