for iIteration = 1:nIterations
    disp(['Num. Clust. Evaluation: Iteration ', num2str(iIteration), ' / ', num2str(CFG.(STAGE_NAME).NumClustEval_nIterations), ' ...' ]);
    evaluationObject = evalclusters( dataToTest, ...
				     CFG.(STAGE_NAME).NumClustEval_methodName, ...
				     CFG.(STAGE_NAME).NumClustEval_criterionType, ...
				     'klist',    CFG.(STAGE_NAME).NumClustEval_kList, ...
				     'Distance', CFG.(STAGE_NAME).NumClustEval_distanceMetric);

    clusteringEvaluation.optNumClustersAllIter(iIteration) = evaluationObject.OptimalK;
    idx = find(evaluationObject.InspectedK == evaluationObject.OptimalK);
    clusteringEvaluation.criterionValues(iIteration) = evaluationObject.CriterionValues(idx);
end % NumClustEval_nIterations
